return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "css",
      "dockerfile",
      "go",
      "gomod",
      "gowork",
      "hcl",
      "html",
      "http",
      "javascript",
      "json",
      "lua",
      "make",
      "markdown",
      "python",
      "regex",
      "ruby",
      "rust",
      "toml",
      "vim",
      "yaml",
      "zig",
    },
    highlight = {
      enable = true,
    },
    rainbow = {
      enable = true,
      extended_mode = true,
      max_file_lines = nil,
    },
  },
}
